name: Build README.md

on:
  push:
  schedule:
    - cron: "23 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - run: npm ci
      - name: Build README.md
        run: |
          npm run build
          cat README.md
      - name: Commit and push changed files
        run: |
          git diff
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git add -A
          git commit -m '🤖 Update README.md' || exit 0
          git push
